---
name: Run terraform plan on PR
on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ENDPOINT_URL: "${{ vars.S3_ENDPOINT }}"
      AWS_ACCESS_KEY_ID: "${{ secrets.S3_ACCESS_KEY }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.S3_SECRET_KEY }}"
      AWS_DEFAULT_REGION: "${{ vars.S3_REGION }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Prepare .terraformrc
        run: sh -c 'echo "${{ vars.TERRAFORM_RC }}" | base64 -d > ~/.terraformrc'

      - name: Prepare tfvars
        run: sh -c 'echo "${{ secrets.TFVARS_FILE }}" | base64 -d > .tfvars'

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -var-file .tfvars
