---
name: Run terraform plan on PR
on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Download state
        env:
          AWS_ENDPOINT_URL: "${{ vars.S3_ENDPOINT }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.S3_ACCESS_KEY }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.S3_SECRET_KEY }}"
          AWS_DEFAULT_REGION: "${{ vars.S3_REGION }}"
        run: |
          aws s3 cp --recursive s3://${{ vars.S3_BUCKET }} ./

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Prepare .terraformrc
        run: echo "${{ vars.TERRAFORM_RC }}" > ~/.terraformrc

      - name: Prepare tfvars
        run: echo "${{ secrets.TFVARS_FILES }}" > .tfvars

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -var-file .tfvars
